<?php
include('../languages/fb.php');
?>
<main class="container">
    <section class="main qui_sommes_nous">
        <div class="texte_accueil">
            <h1><?= $lang['about_accueil_h1']; ?></h1>
        </div>
    </section>
    <div class="information center">
        <img  data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000" src="../images/Logo_20_Years_conetCom_competence.jpg" alt="logo_conetcom">
        <p data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"><?= $lang['about_information_p1']; ?></p>
        <p data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"><?= $lang['about_information_p2']; ?></p>
    </div>
    <section class="about center metier">
        <h2 data-aos="flip-left" data-aos-delay="250" data-aos-duration="1000"><?= $lang['about_metier_h2']; ?></h2>
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000">
            <img src="../images/Prestations_1_Bulding.png" alt="Office de travail">
            <h4><?= $lang['about_metier_h4_1']; ?></h4>
            <p id="d1"><?= $lang['about_metier_span']; ?></p>
            <ul>
                <li id="p1" class="hide">texte a venir</li>
            </ul>
        </div>
        <div data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000">
            <img src="../images/Prestations_2_Datacenter.png" alt="Data Center">
            <h4><?= $lang['about_metier_h4_2']; ?></h4>
            <p id="d2"><?= $lang['about_metier_span']; ?></p>	
            <ul>
                <li id="p2" class="hide">texte a venir</li>
            </ul>			
        </div>
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"> 
            <img src="../images/Prestations_3_Assurance.png" alt="Assurance suivi">
            <h4><?= $lang['about_metier_h4_3']; ?></h4>
            <p id="d3"><?= $lang['about_metier_span']; ?></p>
            <ul>
                <li id="p3" class="hide">texte a venir</li>
            </ul>				
        </div>
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"> 
            <img src="../images/Prestations_4_Fibre_Optique.png" alt="Fibre optique">
            <h4><?= $lang['about_metier_h4_4']; ?></h4>
            <p id="d4"><?= $lang['about_metier_span']; ?></p>
            <ul>
                <li id="p4" class="hide">texte a venir</li>
            </ul>				
        </div>
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"> 
            <img src="../images/Prestations_5_Courant_Faible.png" alt="Courant faible">
            <h4><?= $lang['about_metier_h4_5']; ?></h4>
            <p id="d5"><?= $lang['about_metier_span']; ?></p>
            <ul>
                <li id="p5" class="hide">texte a venir</li>
            </ul>				
        </div> 
        <div data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000">
            <img src="../images/Prestations_6_Courant_Fort.png" alt="Courant fort">
            <h4><?= $lang['about_metier_h4_6']; ?></h4>
            <p id="d6"><?= $lang['about_metier_span']; ?></p>	
            <ul>
                <li id="p6" class="hide">texte a venir</li>
            </ul>			
        </div>       
    </section>
    <div class="adress center" data-aos="flip-up" data-aos-duration="2000">
        <div>
            <h4>Basel BS</h4>
            <h4>conetCom AG</h4>
            <p>Güterstrasse 126</p>
            <p>CH-4053 Basel</p>
            <a href="tel:+41612703111"><p>T +41 61 270 31 11</p></a>
            <a href="tel:+41612703112"><p>F +41 61 270 31 12</p></a>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
        </div>
        <div>
            <h4>Le Lignon GE</h4>
            <h4>conetCom SA</h4>
            <p>Chemin de la Muraille 12</p>
            <p>CH-1219 Le Lignon</p>
            <a href="tel:+41223014866"><p>T +41 22 301 48 66</p></a> 
            <a href="tel:+41223014867"><p>F +41 22 301 48 67</p></a> 
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
        </div>
        <div>
            <h4>Sion VS</h4>
            <h4>conetCom SA</h4>
            <p>Route de Vissigen 68</p>
            <p>CH-1950 Sion</p>
            <a href="tel:+41274558058"><p>T +41 27 455 80 58</p></a> 
            <a href="tel:+41274558059"><p>F +41 27 455 80 59</p></a> 
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
        </div>
        <div>
            <h4>Dübendorf ZH</h4>
            <h4>conetCom ZH</h4>
            <p>Sonnentalstrasse 5</p>
            <p>CH-8600 Dübendorf</p>
            <a href="tel:+41432330540"><p>+41 43 233 05 40</p></a> 
            <a href="tel:+41432330541"><p>+41 43 233 05 41</p></a> 
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
        </div>
    </div>
</main>