<main class="container">
    <h2 class="question"><?= $lang['contact_h2']; ?></h2>
    <div class="formulaires center">
        <h1><?= $lang['contact_h1']; ?></h1>
        <form method="POST" action="contact.php">
        <!-- NOM/PRENOM -->
        <input type="text" name="name" placeholder="Your Name" />
        <!-- MAIL -->
        <input type="email" name="mail"  placeholder="Email Address"/>
        <select name="themes" id="themes" onchange=display()>
            <option value=""><?= $lang['contact_select_jobs1']; ?></option>
            <option id="jobs" value='jobs'>Jobs</option>
            <option value="information">Information</option>
            <option value="project"><?= $lang['contact_select_jobs2']; ?></option>
        </select>
        <!-- JOB -->
        <select class="hide" name="choose_job" id="choosejob" >
            <option value=""><?= $lang['contact_select_choosejobs1']; ?></option>
            <option value='electricien_chantier'><?= $lang['carriere_h3_1']; ?></option>
            <option value="manageur"><?= $lang['carriere_h3_2']; ?></option>
            <option value="ingenieur"><?= $lang['carriere_h3_3']; ?></option>
            <option value="electricien"><?= $lang['carriere_h3_4']; ?></option>
        </select>
        <!-- MESSAGE -->
        <textarea name="message" placeholder="Type your Message"></textarea>
        <!-- ENVOIE -->
        <input type="submit" name="submit" value=<?= $lang['contact_p_envoyer']; ?>>
        </form>
    </div>
    <div>
        <img class="photo_bureau" src="../images/office.jpg" alt="Canapé" data-aos="fade-down" data-aos-duration="2000">
    </div>
    <h2 class="middle" data-aos="fade-down" data-aos-duration="2000"><?= $lang['localisation_h2']; ?></h2>
    <div id="map" data-aos="fade-down" data-aos-duration="2000"></div>
</main>    