<main class="container">
    <form method="post" action="edit_post.php">
        <fieldset>
            <div>
            <label for="message">Message</label>
                <textarea name="message" id="message" cols="30" rows="10"><?= $content['message'] ?></textarea>
            </div>
            <div>
                <label for="theme">Theme</label>
                <textarea name="theme" id="theme" cols="30" rows="10"><?= $content['theme'] ?></textarea>
            </div>
            <button>Modifier</button> 
        </fieldset>
    </form>
</main>