<main class="container">
    <div class="emplois"></div>
    <div class=" return center" data-aos="fade-right" data-aos-delay="250" data-aos-duration="1000"><a href="job.php"><i class="far fa-arrow-alt-circle-left"></i></a></div>
    <article class="emplois_info center" data-aos="fade-right" data-aos-delay="250" data-aos-duration="1000">
        <h2><?= $lang['emplois_h2']; ?></h2>
        <p><?= $lang['emplois_p1_3']; ?></p>
        <p><?= $lang['emplois_p2_3']; ?></p>
        <h3><i class="fas fa-cogs"></i><?= $lang['emplois_h3_competence']; ?></h3>
        <ul>
            <li><?= $lang['emplois_li1_3']; ?></li>
            <li><?= $lang['emplois_li2_3']; ?></li>
            <li><?= $lang['emplois_li3_3']; ?></li>
        </ul>
        <h3><i class="fas fa-calendar-day"></i><?= $lang['emplois_h3_travail']; ?></h3>
        <p><?= $lang['emplois_p4_3']; ?></p>
        <h3><i class="fas fa-globe-americas"></i><?= $lang['emplois_h3_lieu']; ?></h3>
        <p>conetCom SA, Route de Vissigen 68, CH-1950 Sion</p>
        <div class="button_join"><a href="contact.php"><?= $lang['emplois_div']; ?></a></div>
        <p>hello world habibi</p>
    </article>    
</main>