<?php
include('../languages/fb.php');
?>
<main class="container">
    <section class="main qui_sommes_nous">
        <div class="texte_accueil">
            <h1><?php echo $lang['about_accueil_h1']; ?></h1>
        </div>
    </section>
    <article class="information center" data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000">
        <img src="../images/Logo 20 Years conetCom competence.jpg" alt="logo_conetcom">
        <p><?php echo $lang['about_information_p1']; ?></p>
        <p><?php echo $lang['about_information_p2']; ?></p>
    </article>
    <section class="about center metier">
        <h2 data-aos="flip-left" data-aos-delay="250" data-aos-duration="1000"><?php echo $lang['about_metier_h2']; ?></h2>
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000">
            <img src="../images/building.jpg" alt="Office de travail">
            <h4><?php echo $lang['about_metier_h4_1']; ?></h4>
            <p id="d1"><?php echo $lang['about_metier_span']; ?></p>
            <ul>
                <li id="p1" class="hide"><?php echo $lang['about_metier_1_p2']; ?></li>
            </ul>
        </div>
        <div data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000">
            <img src="../images/Datacenter.jpg" alt="Data Room">
            <h4><?php echo $lang['about_metier_h4_2']; ?></h4>
            <p id="d2"><?php echo $lang['about_metier_span']; ?></p>	
            <ul>
                <li id="p2" class="hide"><?php echo $lang['about_metier_2_p2']; ?></li>
            </ul>			
        </div>
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"> 
            <img src="../images/switchh.jpg" alt="Branchement de switch">
            <h4><?php echo $lang['about_metier_h4_3']; ?></h4>
            <p id="d3"><?php echo $lang['about_metier_span']; ?></p>
            <ul>
                <li id="p3" class="hide"><?php echo $lang['about_metier_3_p2']; ?></li>
            </ul>				
        </div>
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"> 
            <img src="../images/disjoncteur.jpg" alt="Disjoncteur">
            <h4><?php echo $lang['about_metier_h4_4']; ?></h4>
            <p id="d4"><?php echo $lang['about_metier_span']; ?></p>
            <ul>
                <li id="p4" class="hide"><?php echo $lang['about_metier_4_p2']; ?></li>
            </ul>				
        </div>
        <div class="service" data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000">
            <h4><?php echo $lang['about_metier_service']; ?></h4>		
        </div> 
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"> 
            <img src="../images/plan_377.jpg" alt="Création de plan">
            <h4><?php echo $lang['about_metier_h4_5']; ?></h4>
            <p id="d5"><?php echo $lang['about_metier_span']; ?></p>
            <ul>
                <li id="p5" class="hide"><?php echo $lang['about_metier_5_p2']; ?></li>
            </ul>				
        </div>        
    </section>
    <div>
        <img class="photo_large mains" src="../images/main.jpg" alt="Poignée de main" data-aos="fade-down" data-aos-duration="2000">
    </div>
    <section class="partenaires center">
        <h2 data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000"><?php echo $lang['partenaires_h2']; ?></h2>
        <article data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000">
            <img class="left" src="../images/Logo_Coop et Magasins.jpg" alt="Logo Coop">
            <p><?php echo $lang['partenaires_1_p']; ?></p>
            <div class="colored-line phone"></div>
        </article>
        <article data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000">
            <img class="right" src="../images/bell-food.png" alt="Logo Bell"></a>
            <p><?php echo $lang['partenaires_2_p']; ?></p>
            <div class="colored-line phone"></div>   
        </article>
        <article data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000">
            <div class="separation"></div>
            <img class="left" src="../images/iwb.png" alt="Logo IWB">
            <p><?php echo $lang['partenaires_3_p']; ?></p>
            <div class="colored-line phone"></div>
        </article>
        <article data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000">
            <div class="separation"></div>
            <img class="right" src="../images/Clariant_logo.png" alt="Logo Clariant">
            <p><?php echo $lang['partenaires_4_p']; ?></p>
        </article>
    </section>
    <div class="morePartner center" data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000">
        <p>Oracle Software (Schweiz) Gmbh, Reishauer AG, Novartis AG, Ticketcorner AG, WIR Bank, Elektra Baselland, Universitäts-Kinderspital beider Basel (UKBB), Theater Basel,
           Vitra AG, Habasit AG, Bardusch AG, Würth AG, Heineken Switzerland, Sympany Versicherungen AG, Helvetia / Nationale Suisse, Office fédéral des constructions et de la Logistique OFCL,
           Etat du Valais, Université de Lausanne, Ecoles de Genève, AMC Construction Management SA, Les Trois Rocs SA, EMS Primeroche Cheseaux …>
        </p>
    </div>
    <div>
        <img class="photo_large" src="../images/office.jpg" alt="Endroit detente" data-aos="fade-up" data-aos-duration="2000">
    </div>
    <div class="adress center" data-aos="flip-up" data-aos-duration="2000">
        <div>
            <h4><?php echo $lang['about_siege_social']; ?> Basel</h4>
            <h4>conetCom AG</h4>
            <p>Güterstrasse 126</p>
            <p>CH-4053 Basel</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41612703111">+41 61 270 31 11</a> 
        </div>
        <div>
            <h4>Filiale Le Lignon Geneve</h4>
            <h4>conetCom SA</h4>
            <p>Chemin de la Muraille 12</p>
            <p>CH-1219 Le Lignon</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41223014866">+41 22 301 48 66</a> 
        </div>
        <div>
            <h4>Filiale Sion VS</h4>
            <h4>conetCom SA</h4>
            <p>Route de Vissigen 68</p>
            <p>CH-1950 Sion</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41274558058">+41 27 455 80 58</a> 
        </div>
        <div>
            <h4>Filiale Dübendorf ZH</h4>
            <h4>conetCom ZH</h4>
            <p>Sonnentalstrasse 5</p>
            <p>CH-8600 Dübendorf</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41274558058">+41 43 233 05 40</a> 
        </div>
    </div>
</main>