<main class="container">
    <div class="flexslider">
        <ul class="slides">
            <li>
                <img src="../images/Home_1_conetCom.png" alt="image slider home"/>
            </li>
            <li>
                <img src="../images/Home_2_Fibre_optique.png" alt="image slider fibre optique"/>
                <p class="milieu">Fibre optique</p>
            </li>
            <li>
                <img src="../images/Home_3_Réseaux_courant_faible.png" alt="image slider courant faible"/>
                <p class="milieu">Réseaux courant faible</p>
            </li>
            <li>
                <img src="../images/Home_4_Installations_électriques.png" alt="image slider installations electriques"/>
                <p class="milieu">Installations électriques</p>
            </li>
        </ul>
    </div>
    <article class="information center">
        <h2 data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?= $lang['acceuil_h2_1']; ?></h2>
        <h2 data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?= $lang['acceuil_h2']; ?></h2>
        <p data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?= $lang['acceuil_p1']; ?></p>
        <p data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?= $lang['acceuil_p2']; ?></p>
        <p data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?= $lang['acceuil_p3']; ?></p>
        <p data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?= $lang['acceuil_p4']; ?></p>
        <p data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?= $lang['acceuil_p5']; ?></p>
    </article>
    <div class="about center" data-aos="zoom-in-up" data-aos-duration="2000">
        <article>
            <h3><?= $lang['about_h3_1']; ?></h3>
            <img src="../images/fibre2.png" alt="Fibre">
            <a href="about.php"><?= $lang['about_a']; ?></a>
        </article>
        <article>
            <h3><?= $lang['about_h3_2']; ?></h3>
            <img src="../images/courantfort.jpg" alt="Courant faible">						
            <a href="about.php"><?= $lang['about_a']; ?></a>						
        </article>
        <article>
            <h3><?= $lang['about_h3_3']; ?></h3>
            <img src="../images/courantfaible.jpg" alt="Courant fort">
            <a href="about.php"><?= $lang['about_a']; ?></a>					
        </article>
    </div>
    <div class="img_centre">
    <img data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000" src="../images/logo20ans.jpg" alt="Logo 20 ans conetCom">
    </div>
    <h2 class="text_align" data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?= $lang['acceuil_h2_2']; ?></h2>
    <div class="autoplay">
            <div>
               <img src="../logo/Logo_Amc.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_Bank_CLER.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_Bardusch.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_BellFood_Group.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_Christ.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_Clariant.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_Coop_1.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_Coop_2_Restaurant.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_Coop_3_Brico_Loisir.png" alt="Logo"/>
            </div>
            <div>
               <img src="../logo/Logo_Coop_4_at_home.png" alt="Logo"/>
            </div>
            <div>
                <img src="../logo/Logo_EMS_Primeroche_Fondation.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Getec_Parkswiss.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Habasit.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Import_Parfumerie.svg.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Interdiscount.svg.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_IWB.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Les_Trois_Rocs.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Livique.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Lumimart.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Office_Federal_Constructions_et_de_la_logistique.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Reishauer.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Sapori_d'Italia.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_THBS.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_Ticketcorner.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_UKBB.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_UNIL.svg.png" alt="Logo">
            </div>
            <div>
                <img src="../logo/Logo_WIR_Bank.png" alt="Logo">
            </div>
   </div>
    <div class="adress center" data-aos="flip-up" data-aos-duration="2000">
        <div>
            <h4>Basel BS</h4>
            <h4>conetCom AG</h4>
            <p>Güterstrasse 126</p>
            <p>CH-4053 Basel</p>
            <a href="tel:+41612703111"><p>T +41 61 270 31 11</p></a>
            <a href="tel:+41612703112"><p>F +41 61 270 31 12</p></a>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
        </div>
        <div>
            <h4>Le Lignon GE</h4>
            <h4>conetCom SA</h4>
            <p>Chemin de la Muraille 12</p>
            <p>CH-1219 Le Lignon</p>
            <a href="tel:+41223014866"><p>T +41 22 301 48 66</p></a> 
            <a href="tel:+41223014867"><p>F +41 22 301 48 67</p></a> 
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
        </div>
        <div>
            <h4>Sion VS</h4>
            <h4>conetCom SA</h4>
            <p>Route de Vissigen 68</p>
            <p>CH-1950 Sion</p>
            <a href="tel:+41274558058"><p>T +41 27 455 80 58</p></a> 
            <a href="tel:+41274558059"><p>F +41 27 455 80 59</p></a> 
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
        </div>
        <div>
            <h4>Dübendorf ZH</h4>
            <h4>conetCom ZH</h4>
            <p>Sonnentalstrasse 5</p>
            <p>CH-8600 Dübendorf</p>
            <a href="tel:+41432330540"><p>+41 43 233 05 40</p></a> 
            <a href="tel:+41432330541"><p>+41 43 233 05 41</p></a> 
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
        </div>
    </div>
</main>
