<?php
include('../languages/fb.php');
?>
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- STYLE -->
    <link rel="stylesheet" href="../CSS/style.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="../slick/slick-theme.css"/>
    <link rel="stylesheet" href="../woocommerce-FlexSlider-690832b/flexslider.css" type="text/css">
    <!-- JS -->
    <script src="../JS/main.js" defer></script>
    <script src="../JS/maps.js" defer></script>
    <script src="../JS/formulaire.js" defer></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCncH65p90tDp4ICqq_4w18SKefgz8FhV0&callback=initMap" defer></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="../slick/slick.min.js"></script>
    <script src="../woocommerce-FlexSlider-690832b/jquery.flexslider.js"></script>
    <!-- FONT AWESOME -->
    <script src="https://kit.fontawesome.com/3903820350.js" crossorigin="anonymous"></script>
    <!-- LOGO SITE -->
    <link rel="shortcut icon" type="image/ico" href="../images/logo_conet.ico"/>
    <!-- GOOGLE FONT-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>conetCom - Competence for Network and Communication</title>
</head>
<body>
    <header class="header">
        <div id="menu-button" class="close"></div> 
            <nav id="menu">    
                <a href="index"><?= $lang['one']; ?></a>
                <a href="about"><?= $lang['two']; ?></a>
                <a href="realisations"><?= $lang['six']; ?></a>
                <a href="job"><?= $lang['four']; ?></a>
                <a href="contact"><?= $lang['five']; ?></a>
            </nav> 
        <div class="conetcom">
            <a href="index.php"><img src="../images/logo_ecriture.png" alt="Logo de l'entreprise Conectcom"></a>     
        </div> 
        <div class="trad">
                <?= " <a  href='".$_SERVER['SCRIPT_NAME']."?lang=de'>DE</a>"; ?>
                <?= " <a  href='".$_SERVER['SCRIPT_NAME']."?lang=fr'>FR</a>"; ?>
                
            </div>  
    </header>
        <!-- Chargement du template (le fichier .phtml spécifique à la page) -->
        <?php require $template . '.phtml' ?>
    <footer class="container">
        <div>
            <p>Copyright © 2021 conetCom® | <a href="#">by Axel</a></p>
        </div>
    </footer> 
</body>